insert into hotel_brands (brand_name, address_id) values ('Bahringer, Weissnat and Robel', 75);
insert into hotel_brands (brand_name, address_id) values ('Larson, Weimann and Mueller', 41);
insert into hotel_brands (brand_name, address_id) values ('Nicolas, Denesik and Schuster', 72);
insert into hotel_brands (brand_name, address_id) values ('Padberg and Sons', 72);

insert into office_emails (hotel_brand_id, email_id) values (3, 57);
insert into office_emails (hotel_brand_id, email_id) values (4, 58);
insert into office_emails (hotel_brand_id, email_id) values (5, 59);
insert into office_emails (hotel_brand_id, email_id) values (6, 60);

insert into office_phones (hotel_brand_id, phone_number_id) values (3, 57);
insert into office_phones (hotel_brand_id, phone_number_id) values (4, 58);
insert into office_phones (hotel_brand_id, phone_number_id) values (5, 59);
insert into office_phones (hotel_brand_id, phone_number_id) values (6, 60);

insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Flatley and Sons Hotel', 27, 1, 3);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Haag and Sons Hotel', 66, 1, 3);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Rohan-Welch Hotel', 69, 4, 3);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Schuster, Nolan and Gorczany Hotel', 61, 2, 3);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Bergstrom LLC Hotel', 6, 1, 3);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Padberg and Sons Hotel', 83, 2, 3);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Klocko-Waelchi Hotel', 97, 1, 4);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Barrows LLC Hotel', 63, 2, 4);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Mayert-Bechtelar Hotel', 33, 3, 4);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Kuphal-Kertzmann Hotel', 8, 4, 4);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Grady Inc Hotel', 94, 1, 4);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Dare, Christiansen and Kling Hotel', 65, 2, 4);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Satterfield, Nikolaus and Klein Hotel', 1, 2, 5);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Hessel, Prosacco and Bradtke Hotel', 4, 5, 5);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Osinski LLC Hotel', 91, 1, 5);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Roob, Ratke and Wiegand Hotel', 65, 4, 5);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Kuhic LLC Hotel', 18, 4, 5);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Veum and Sons Hotel', 53, 4, 5);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Flatley Group Hotel', 73, 2, 6);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Fay, Toy and Koepp Hotel', 51, 4, 6);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Weimann Inc Hotel', 96, 1, 6);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Jast-Reynolds Hotel', 39, 5, 6);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Rath-Kuvalis Hotel', 92, 1, 6);
insert into hotels (hotel_name, address_id, star_category, hotel_brand_id) values ('Gusikowski and Sons Hotel', 83, 4, 6);

insert into hotel_emails (hotel_id, email_id) values (4, 103);
insert into hotel_emails (hotel_id, email_id) values (5, 104);
insert into hotel_emails (hotel_id, email_id) values (6, 105);
insert into hotel_emails (hotel_id, email_id) values (7, 106);
insert into hotel_emails (hotel_id, email_id) values (8, 107);
insert into hotel_emails (hotel_id, email_id) values (9, 108);
insert into hotel_emails (hotel_id, email_id) values (10, 109);
insert into hotel_emails (hotel_id, email_id) values (11, 110);
insert into hotel_emails (hotel_id, email_id) values (12, 111);
insert into hotel_emails (hotel_id, email_id) values (13, 112);
insert into hotel_emails (hotel_id, email_id) values (14, 113);
insert into hotel_emails (hotel_id, email_id) values (15, 114);
insert into hotel_emails (hotel_id, email_id) values (16, 115);
insert into hotel_emails (hotel_id, email_id) values (17, 116);
insert into hotel_emails (hotel_id, email_id) values (18, 117);
insert into hotel_emails (hotel_id, email_id) values (19, 118);
insert into hotel_emails (hotel_id, email_id) values (20, 119);
insert into hotel_emails (hotel_id, email_id) values (21, 120);
insert into hotel_emails (hotel_id, email_id) values (22, 121);
insert into hotel_emails (hotel_id, email_id) values (23, 122);
insert into hotel_emails (hotel_id, email_id) values (24, 123);
insert into hotel_emails (hotel_id, email_id) values (25, 124);
insert into hotel_emails (hotel_id, email_id) values (26, 125);
insert into hotel_emails (hotel_id, email_id) values (27, 126);

insert into hotel_phones (hotel_id, phone_number_id) values (4, 103);
insert into hotel_phones (hotel_id, phone_number_id) values (5, 104);
insert into hotel_phones (hotel_id, phone_number_id) values (6, 105);
insert into hotel_phones (hotel_id, phone_number_id) values (7, 106);
insert into hotel_phones (hotel_id, phone_number_id) values (8, 107);
insert into hotel_phones (hotel_id, phone_number_id) values (9, 108);
insert into hotel_phones (hotel_id, phone_number_id) values (10, 109);
insert into hotel_phones (hotel_id, phone_number_id) values (11, 110);
insert into hotel_phones (hotel_id, phone_number_id) values (12, 111);
insert into hotel_phones (hotel_id, phone_number_id) values (13, 112);
insert into hotel_phones (hotel_id, phone_number_id) values (14, 113);
insert into hotel_phones (hotel_id, phone_number_id) values (15, 114);
insert into hotel_phones (hotel_id, phone_number_id) values (16, 115);
insert into hotel_phones (hotel_id, phone_number_id) values (17, 116);
insert into hotel_phones (hotel_id, phone_number_id) values (18, 117);
insert into hotel_phones (hotel_id, phone_number_id) values (19, 118);
insert into hotel_phones (hotel_id, phone_number_id) values (20, 119);
insert into hotel_phones (hotel_id, phone_number_id) values (21, 120);
insert into hotel_phones (hotel_id, phone_number_id) values (22, 121);
insert into hotel_phones (hotel_id, phone_number_id) values (23, 122);
insert into hotel_phones (hotel_id, phone_number_id) values (24, 123);
insert into hotel_phones (hotel_id, phone_number_id) values (25, 124);
insert into hotel_phones (hotel_id, phone_number_id) values (26, 125);
insert into hotel_phones (hotel_id, phone_number_id) values (27, 126);

insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (4, 'Andréanne', 'Up-sized contextually-based portal', 869.11, true, true, false, false, false, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (4, 'Géraldine', 'Synchronised logistical hub', 1449.03, false, true, false, false, false, true, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (4, 'Hélèna', 'Switchable real-time middleware', 150.15, true, true, true, true, true, true, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (4, 'Lauréna', 'Proactive attitude-oriented capability', 658.45, false, false, true, true, true, true, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (4, 'Daphnée', 'Exclusive interactive alliance', 421.72, true, false, false, true, true, false, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (5, 'Angèle', 'Horizontal mobile analyzer', 1216.99, true, true, true, true, false, false, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (5, 'Stéphanie', 'Fully-configurable 6th generation benchmark', 772.91, true, true, true, true, true, true, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (5, 'Frédérique', 'Assimilated explicit system engine', 541.52, true, false, false, false, false, false, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (5, 'Bérangère', 'Stand-alone background architecture', 179.88, false, false, false, false, false, false, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (5, 'Léonore', 'Triple-buffered content-based software', 1095.04, false, false, true, false, true, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (6, 'Estée', 'Stand-alone bandwidth-monitored challenge', 573.68, true, false, true, false, true, true, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (6, 'Chloé', 'Pre-emptive radical instruction set', 567.41, false, false, false, false, false, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (6, 'Félicie', 'Balanced modular collaboration', 190.37, true, true, false, true, false, true, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (6, 'Dorothée', 'Diverse zero tolerance benchmark', 835.39, false, false, false, true, false, true, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (6, 'Maï', 'Optional value-added support', 750.9, true, true, true, false, false, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (7, 'Lucrèce', 'Robust dynamic circuit', 198.11, false, false, true, true, true, true, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (7, 'Bérengère', 'Stand-alone contextually-based benchmark', 587.79, true, true, true, true, false, true, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (7, 'Cinéma', 'Total maximized protocol', 566.53, true, false, true, true, false, false, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (7, 'Angèle', 'Synchronised grid-enabled policy', 1102.49, false, false, false, false, false, false, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (7, 'Annotée', 'Persistent bottom-line standardization', 146.1, true, false, true, true, true, false, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (8, 'Eléonore', 'Cross-group zero administration challenge', 900.69, true, false, false, true, false, true, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (8, 'Eléa', 'Function-based asynchronous attitude', 681.91, true, true, true, false, true, false, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (8, 'Salomé', 'Versatile value-added leverage', 940.17, true, true, false, true, true, false, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (8, 'Kuí', 'Grass-roots high-level forecast', 1088.55, false, true, true, false, true, true, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (8, 'Mélys', 'Open-architected dedicated model', 1112.09, false, false, true, true, false, false, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (9, 'Göran', 'Right-sized methodical matrix', 1382.05, true, true, false, true, false, true, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (9, 'Laïla', 'Digitized dynamic concept', 1477.3, false, false, true, true, false, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (9, 'Marie-josée', 'Profound context-sensitive circuit', 299.4, false, false, true, false, true, false, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (9, 'Dorothée', 'Organized tangible functionalities', 119.74, false, true, false, true, true, false, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (9, 'Clémence', 'Implemented actuating middleware', 818.06, true, true, true, false, true, false, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (10, 'Zhì', 'Focused client-driven access', 1158.43, false, true, true, true, false, true, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (10, 'Angèle', 'Phased foreground concept', 537.31, false, false, false, false, true, true, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (10, 'Amélie', 'Streamlined zero defect internet solution', 707.08, true, true, false, true, true, false, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (10, 'Erwéi', 'Multi-lateral optimal Graphical User Interface', 547.1, true, false, true, true, true, false, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (10, 'Lauréna', 'Quality-focused cohesive forecast', 169.63, false, false, true, false, true, false, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (11, 'Almérinda', 'Integrated system-worthy array', 1095.73, false, true, true, true, false, true, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (11, 'Kallisté', 'Assimilated tertiary projection', 696.83, true, false, false, false, false, false, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (11, 'Maëlyss', 'Operative executive matrix', 500.37, true, false, false, false, true, true, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (11, 'Léandre', 'Robust discrete open system', 1444.55, true, false, true, false, false, false, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (11, 'Mélanie', 'Focused attitude-oriented knowledge user', 934.0, false, true, true, false, false, true, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (12, 'Eloïse', 'Up-sized transitional portal', 333.57, true, false, false, false, true, false, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (12, 'Yú', 'Virtual background Graphic Interface', 806.19, false, true, true, true, false, true, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (12, 'Marie-ève', 'Right-sized dynamic methodology', 1152.78, false, true, false, false, true, true, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (12, 'Françoise', 'Self-enabling holistic product', 889.06, false, true, true, false, true, true, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (12, 'Björn', 'Configurable tertiary implementation', 1216.5, false, false, true, true, true, false, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (13, 'Intéressant', 'Face to face multimedia ability', 687.39, true, false, false, false, true, true, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (13, 'Marie-noël', 'Stand-alone global pricing structure', 1020.3, false, true, false, false, false, true, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (13, 'Tán', 'Grass-roots contextually-based parallelism', 429.67, true, true, false, false, false, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (13, 'Andréanne', 'Compatible mission-critical approach', 1283.21, true, false, false, true, false, false, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (13, 'Lèi', 'Customer-focused 24 hour product', 153.14, true, false, false, false, false, false, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (14, 'Maéna', 'Assimilated bi-directional firmware', 1127.56, false, true, true, true, false, false, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (14, 'Marie-ève', 'Fully-configurable 24 hour time-frame', 1001.69, true, false, false, true, false, true, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (14, 'Mélia', 'Fully-configurable motivating migration', 557.26, true, false, true, true, false, false, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (14, 'Pénélope', 'Progressive zero defect collaboration', 800.16, false, false, true, false, false, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (14, 'Ruì', 'Extended explicit internet solution', 555.1, true, true, true, true, false, false, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (15, 'Yénora', 'Expanded maximized conglomeration', 1491.45, true, true, true, true, false, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (15, 'Marlène', 'Fundamental 5th generation data-warehouse', 208.01, false, false, false, true, false, true, false, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (15, 'Yénora', 'Cloned tertiary project', 1478.28, false, false, true, true, true, true, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (15, 'Adèle', 'Reactive leading edge secured line', 1179.09, true, true, true, false, true, true, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (15, 'Aimée', 'Streamlined methodical forecast', 1144.04, true, false, false, false, true, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (16, 'Nélie', 'Progressive regional projection', 260.66, true, true, true, false, true, true, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (16, 'Vénus', 'Cross-platform grid-enabled synergy', 311.63, true, false, false, true, true, true, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (16, 'Nélie', 'Persistent grid-enabled strategy', 391.87, true, true, false, true, false, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (16, 'Mårten', 'Synchronised logistical initiative', 1345.12, false, true, false, true, true, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (16, 'Océane', 'Re-contextualized value-added migration', 290.12, true, false, true, false, false, false, true, false);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (17, 'Léandre', 'Visionary coherent strategy', 584.19, true, false, true, true, false, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (17, 'Nadège', 'Integrated system-worthy info-mediaries', 1484.02, true, false, true, true, true, true, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (17, 'Estève', 'Programmable systematic array', 474.25, true, false, false, false, false, false, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (17, 'Yáo', 'Implemented discrete Graphical User Interface', 739.45, false, true, true, false, true, true, false, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (17, 'Léana', 'Business-focused clear-thinking moderator', 1097.16, false, true, false, false, false, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (18, 'Lorène', 'Persistent reciprocal application', 1468.44, true, false, true, true, false, false, true, true);
insert into rooms (hotel_id, room_title, room_description, price, ocean_view, mountain_view, can_extend, has_tv, has_ac, has_mini_bar, has_hairdryer, has_wifi) values (18, 'Yú', 'Horizontal empowering firmware', 215.75, true, true, false, true, true, true, false, true);
